-- =====================================================================
-- v3.0 — Admin Panel + çoklu proje/kullanıcı temel şeması (Faz 0).
-- Oracle Database (23c+ syntax — IDENTITY sütunları kullanır).
--
-- NEDEN bu 5 tablo birlikte: hepsi birbirine bağlı (Kullanıcı -> Proje
-- ataması -> Senaryo -> Koşum), o yüzden Faz 0'da hepsini birden
-- oluşturuyoruz — ileriki fazlar (login/LDAP/izin kontrolü/admin UI)
-- bu tabloların ÜZERİNE özellik ekler, şemayı yeniden tasarlamaz.
--
-- NOT — Agent Behavior eşikleri (max steps, min confidence vb.) BİLEREK
-- bu ilk şemaya dahil edilmedi (Faz 5'te WEB_PROJECTS'e sütun olarak
-- eklenecek) — şimdiden şişirmeyelim.
-- =====================================================================

-- ---------------------------------------------------------------------
-- WEB_USERS — hem yerel (LOCAL) hem LDAP kullanıcıları TEK tabloda tutulur.
-- LDAP kullanıcılarında PASSWORD_HASH NULL kalır: kimlik doğrulama LDAP
-- sunucusuna karşı yapılır, şifre bizim tarafımızda HİÇ saklanmaz.
-- ---------------------------------------------------------------------
CREATE TABLE WEB_USERS (
  USER_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  USERNAME       VARCHAR2(200) NOT NULL,
  USER_TYPE      VARCHAR2(20)  NOT NULL,
  PASSWORD_HASH  VARCHAR2(255),
  DISPLAY_NAME   VARCHAR2(200),
  ROLE           VARCHAR2(20)  NOT NULL,
  CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),
  CONSTRAINT CK_USERS_TYPE CHECK (USER_TYPE IN ('LOCAL', 'LDAP')),
  CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('ADMIN', 'MEMBER'))
);

-- ---------------------------------------------------------------------
-- WEB_PROJECTS — admin tarafından oluşturulur. Grid URL, paralel koşum
-- limiti ve LLM modeli proje bazlı burada tutulur (bkz. sohbet notu:
-- "model bilgisi admin panelinde manuel girilecek" — proje ayarı).
-- Bugünkü .env'deki SELENIUM_GRID_URL / OPENROUTER_MODEL vb. global
-- değerlerin proje bazlı karşılığı.
-- ---------------------------------------------------------------------
CREATE TABLE WEB_PROJECTS (
  PROJECT_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  PROJECT_NAME       VARCHAR2(200) NOT NULL,
  GRID_URL           VARCHAR2(500),
  MAX_PARALLEL_RUNS  NUMBER,
  LLM_MODEL          VARCHAR2(200),
  CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY         NUMBER,
  CONSTRAINT UQ_PROJECTS_NAME UNIQUE (PROJECT_NAME),
  CONSTRAINT FK_PROJECTS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES WEB_USERS (USER_ID)
);

-- ---------------------------------------------------------------------
-- WEB_PROJECT_MEMBERS — bir kullanıcının hangi projelere atandığı. Bu
-- tablo, "atanmayan kullanıcı o projenin testlerini göremez/
-- değiştiremez" izin kontrolünün temelidir (bkz. Faz 4).
-- ---------------------------------------------------------------------
CREATE TABLE WEB_PROJECT_MEMBERS (
  PROJECT_ID   NUMBER NOT NULL,
  USER_ID      NUMBER NOT NULL,
  ASSIGNED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PROJECT_MEMBERS PRIMARY KEY (PROJECT_ID, USER_ID),
  CONSTRAINT FK_PM_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES WEB_PROJECTS (PROJECT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_PM_USER FOREIGN KEY (USER_ID) REFERENCES WEB_USERS (USER_ID) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- WEB_SCENARIOS — bugünkü GeneratedTestStore'un (index.json) DB karşılığı.
-- Her senaryo BİR projeye ait. SCENARIO_NAME kullanıcının verdiği isim
-- (bkz. bugünkü displayName/testName), SCENARIO_TEXT AI'a verilen doğal
-- dil talimattır (bugünkü `scenario` alanı).
-- ---------------------------------------------------------------------
CREATE TABLE WEB_SCENARIOS (
  SCENARIO_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  PROJECT_ID     NUMBER NOT NULL,
  SCENARIO_NAME  VARCHAR2(200) NOT NULL,
  SCENARIO_TEXT  CLOB NOT NULL,
  TARGET_URL     VARCHAR2(1000) NOT NULL,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY     NUMBER,
  CONSTRAINT FK_SCENARIOS_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES WEB_PROJECTS (PROJECT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SCENARIOS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES WEB_USERS (USER_ID)
);

-- ---------------------------------------------------------------------
-- WEB_RUNS — her koşum (execution). PROJECT_ID, SCENARIO_ID üzerinden
-- türetilebilir olsa da sorgu kolaylığı için (proje bazlı listeleme
-- her seferinde WEB_SCENARIOS'a JOIN gerektirmesin diye) ayrıca tutulur.
--
-- Sohbet notundaki alan eşlemesi:
--   ProjectName        -> PROJECT_ID (join ile WEB_PROJECTS.PROJECT_NAME)
--   ScenarioName        -> join ile WEB_SCENARIOS.SCENARIO_NAME
--   Status              -> STATUS
--   WhoStarted          -> STARTED_BY (join ile WEB_USERS.DISPLAY_NAME)
--   Date (çalışma süresi) -> STARTED_AT + FINISHED_AT
--   Date of created scenario -> join ile WEB_SCENARIOS.CREATED_AT
--   PlatformName        -> BROWSER_ENGINE (chromium/firefox/webkit)
--   Scenario steps JSON -> STEPS_JSON (CLOB)
-- ---------------------------------------------------------------------
CREATE TABLE WEB_RUNS (
  RUN_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  SCENARIO_ID    NUMBER NOT NULL,
  PROJECT_ID     NUMBER NOT NULL,
  STATUS         VARCHAR2(20) NOT NULL,
  BROWSER_ENGINE VARCHAR2(20) NOT NULL,
  STARTED_AT     TIMESTAMP NOT NULL,
  FINISHED_AT    TIMESTAMP,
  STARTED_BY     NUMBER,
  STEPS_JSON     CLOB,
  CONSTRAINT CK_RUNS_STATUS CHECK (STATUS IN ('pending', 'running', 'passed', 'failed', 'error', 'cancelled')),
  CONSTRAINT CK_RUNS_BROWSER CHECK (BROWSER_ENGINE IN ('chromium', 'firefox', 'webkit')),
  CONSTRAINT FK_RUNS_SCENARIO FOREIGN KEY (SCENARIO_ID) REFERENCES WEB_SCENARIOS (SCENARIO_ID) ON DELETE CASCADE,
  CONSTRAINT FK_RUNS_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES WEB_PROJECTS (PROJECT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_RUNS_STARTED_BY FOREIGN KEY (STARTED_BY) REFERENCES WEB_USERS (USER_ID)
);

-- Sık sorgulanacak alanlar için index'ler (proje bazlı listeleme,
-- senaryo bazlı koşum geçmişi, kullanıcı bazlı "benim koşumlarım").
CREATE INDEX IX_SCENARIOS_PROJECT ON WEB_SCENARIOS (PROJECT_ID);
CREATE INDEX IX_RUNS_PROJECT ON WEB_RUNS (PROJECT_ID);
CREATE INDEX IX_RUNS_SCENARIO ON WEB_RUNS (SCENARIO_ID);
CREATE INDEX IX_RUNS_STARTED_BY ON WEB_RUNS (STARTED_BY);
